### ISSUE TITLE
Doesn't work on mono/Mac because of the custom compression library

### ISSUE THREAD

**Issue by cotyar** [rflechner/Suave.Swagger#10]
### Description

Fails on start with "Assembly not found" exception when run on mono/Mac.
The reason is SharpZipLib. 

I've got a fix [here](https://github.com/cotyar/Suave.Swagger/commit/f99c3c482ef4a91a34a4b41cb9e3dc4780caf855) but, sorry, didn't have a chance yet to prepare a proper PR.

**Comment by rflechner** [comment]
Thanks for bug report.
It's fixed by PR #9

**Comment by cotyar** [comment]
Great! Thanks a lot!
Sorry for not preparing the PR myself

Cheers
Yuriy
