### ISSUE TITLE
Is it possible to compose multiple routes

### ISSUE THREAD

**Issue by rkosafo** [rflechner/Suave.Swagger#11]
### Description

Given two or more definitions with

    let controllerA = swagger { ... } 
    let controllerB = swagger { ... }

Is there a way to combine them to get something like

    let api = swagger { ... controllerA ... controllerB }

### Known workarounds

Define everything within one big swagger computation.

### Related information 

* Operating system: Windows 10
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by alexey-belous** [comment]
@rkosafo, did you tried to use this approach?
```
let controllerA = swagger { ... }
let controllerB = swagger { ... }
let api = swagger { 
     yield controllerA
     yield controllerB 
}
```

It's works for me.

**Comment by rkosafo** [comment]
@alexey-belous Tried it and it worked.
