### ISSUE TITLE
How do set the description for parameters

### ISSUE THREAD

**Issue by rkosafo** [rflechner/Suave.Swagger#12]
### Description

How does one set the description for parameters?

The current method does not seem to provide a field for that update. What am I missing?

    yield parameter "type" Of route (fun p -> { p with Type=Some typeof<int>; In=Query})

### Related information 

* Operating system: Windows 10
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by rkosafo** [comment]
The field is missing. I've currently updated @alexey-belous 's PR to add support. Will try to publish a PR later if needed.

**Comment by rflechner** [comment]
Ok, I close this issue because it seems to be working now
