### ISSUE TITLE
Documenting Parameters from urlFormat

### ISSUE THREAD

**Issue by rkosafo** [rflechner/Suave.Swagger#13]
### Description

How does one document the parameters generated by `urlFormat` (e.g. set the name)?

### Related information 

* Operating system: Windows 10
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by rflechner** [comment]
I will implement this.
For the moment, we have to use `getOf` like here: https://github.com/rflechner/Suave.Swagger/blob/develop/examples/Suave.Swagger.PetStoreAPi/Program.fs#L143

**Comment by rflechner** [comment]
Released in version 2.2.0
