### ISSUE TITLE
How to specify Input type

### ISSUE THREAD

**Issue by rkosafo** [rflechner/Suave.Swagger#14]
### Description

Is there a way to specify the Input type for a parameter? This will help in instances where a multiple-line input (text area) is desired.

### Related information 

* Operating system: Windows 10
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by rflechner** [comment]
Yes you can we things like this:

`yield parameter "uuid" Of route (fun p -> { p with Type = (Some typeof<Guid>); In=Path })`

or 

`yield parameter "body" Of route (fun p -> { p with Type = (Some typeof<PetCategory>); In=Body })`
