### ISSUE TITLE
How to specify a parameter containing an array of objects?

### ISSUE THREAD

**Issue by tejagsp** [rflechner/Suave.Swagger#22]
### Description

Unable to get the documentation right for a type which consists an array of objects.

### Repro steps

Please provide the steps required to reproduce the problem

1. I have types:

    [<CLIMutable>]
    type A =
        { a1: float<deg>
          a2 : float<deg>
          a3 : string option }

    [<CLIMutable>]
    type B =
        { b1: int
          b2 : A array
          b3 : string
          b4 : float<m/s> }

2.  And, in the documentation I use 

   for route in docBuildState do
     xxxxxxxxxxxxxxxxxxxxxxxxx
     yield parameter "Voyage" Of route (fun p ->
                    { p with Type = (Some typeof<B>); In=Body })

3. The documentation returns an error:

Errors

Resolver error at paths./something.post.parameters.0.schema.properties.b2.properties.SyncRoot.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/Object does not exist in document
Resolver error at definitions.B.properties.b2.properties.SyncRoot.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/Object does not exist in document
Resolver error at definitions.A[].properties.SyncRoot.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/Object does not exist in document

### Expected behavior

Models to return as expected

### Actual behavior

Please provide a description of the actual behavior you observe. 

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

* Windows 10
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by ChrSteinert** [comment]
I had the same problem. I currently manually edited my json file to fix this.
In the end it should look like this:
```
    "B": {
      "type": "object",
      "properties": {
        "b2": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/A"
          },
          …
        },
```

At least a work around for now

**Comment by ChrSteinert** [comment]
The Problem is, that [HERE](https://github.com/rflechner/Suave.Swagger/blob/develop/src/Suave.Swagger/Swagger.fs#L407) does not discern for nested objects and enumeration types (Arrays, Lists, etc.)

**Comment by tejagsp** [comment]
Thanks for the comment.

Yes, I did the same editing the JSON file.

**Comment by tejagsp** [comment]
Closed, as it is as designed
