### ISSUE TITLE
Grouping of route documentation

### ISSUE THREAD

**Issue by lawrencetaylor** [rflechner/Suave.Swagger#5]
Is it possible to have the documentation for routes grouped by "endpoints"? 

For example, if I look on http://petstore.swagger.io/#/ the routes have been grouped according to the entities they act upon:

![image](https://cloud.githubusercontent.com/assets/3350920/19931292/d8b1677c-a103-11e6-84d5-86ccff700392.png)

In the examples for Suave.Swagger, all route documentation is grouped under "default":

![image](https://cloud.githubusercontent.com/assets/3350920/19931326/06f8acc6-a104-11e6-917d-d123250cd9e2.png)

 Is there a way to change this - or if not could you give me some pointers as to what I would need to change in the code so I could work on a pull request?

**Comment by lawrencetaylor** [comment]
I've opened up a [pull request](https://github.com/rflechner/Suave.Swagger/pull/6) which aims to fix this (and one other issue detailed in the comments of the pull request).

**Comment by rflechner** [comment]
Hi, your PR is merged.
Thank you
